version: 2
jobs:
  build:
    working_directory: ~/circleci-demo-ruby-rails
    docker:
      - image: circleci/ruby:2.4.1-node
      - image: postgres:9.4.1
    steps:
      - checkout
      - run: bundle install --path vendor/bundle
      - run: bundle exec rake db:drop
      - run: bundle exec rake db:create RAILS_ENV=test
      - run: bundle exec rake db:migrate RAILS_ENV=test
      - run: bundle exec rake test
      - run: bundle exec rspec spec

     
